# -*- coding: utf-8 -*-
"""lab01-me524.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9D3-TEPRh642i7M5_8VEEx0lMcMZwJ6

**1. Download do CSV**
"""

import os

# Baixa o CSV do repositório (sobrescreve se já existir)
url_csv = "https://raw.githubusercontent.com/juliafolgueral/me524-lab01-brasileirao/main/brasileirao_2026.csv"
!wget -q -O brasileirao_2026.csv {url_csv}

print("\nArquivo baixado com sucesso:")
!ls brasileirao_2026.csv

"""**2. Imports, configuração e funções**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 0. Configuração

CSV_PATH = "brasileirao_2026.csv"   # baixado na célula de download (GitHub)
N_SIM = 10000                       # simulações Monte Carlo
N_BOOT = 2000                       # réplicas bootstrap
N_REBAIXADOS = 4                    # quantos times caem (últimas posições)
SEED = 42


# 1. Leitura dos dados

# Lê o CSV de jogos
def load_data(path):
    df = pd.read_csv(path)
    df.columns = [c.strip() for c in df.columns]
    return df

# Lista ordenada com todas as equipes do campeonato.
def get_teams(df):
    return sorted(set(df["time_mandante"]) | set(df["time_visitante"]))

# Apenas os jogos já realizados (com placar).
def played_games(df):
    return df.dropna(subset=["gols_mandante", "gols_visitante"])


# 2. Estimação dos parâmetros theta (ataque) e phi (defesa)

""" Estima-se, para cada time, a partir dos jogos já realizados:
      - theta = média de gols marcados por jogo (poder de ataque)
      - phi   = média de gols sofridos por jogo (fragilidade defensiva)
    Além disso, times sem jogos recebem theta = phi = 1.0 (valor neutro).
    Este código retorna um DataFrame indexado por time."""
def estimate_parameters(df):
    played = played_games(df)

    rows = []
    for team in get_teams(df):
        home = played[played["time_mandante"] == team]
        away = played[played["time_visitante"] == team]

        gols_marcados = pd.concat([home["gols_mandante"], away["gols_visitante"]])
        gols_sofridos = pd.concat([home["gols_visitante"], away["gols_mandante"]])

        n_jogos = len(gols_marcados)
        theta = gols_marcados.mean() if n_jogos > 0 else 1.0
        phi = gols_sofridos.mean() if n_jogos > 0 else 1.0

        rows.append({"time": team, "theta": theta, "phi": phi, "jogos_disputados": n_jogos})

    return pd.DataFrame(rows).set_index("time")


""" Adiciona a `params` os parâmetros da atividade extra:
      - eta_m = (média de gols do time jogando em casa) / theta
      - eta_v = (média de gols do time jogando fora)    / theta
    Lembrando que se o time não jogou naquele mando, usa-se theta (eta = 1)."""
def estimate_extra_parameters(df, params):
    played = played_games(df)

    media_casa = played.groupby("time_mandante")["gols_mandante"].mean()
    media_fora = played.groupby("time_visitante")["gols_visitante"].mean()

    out = params.copy()
    media_casa = media_casa.reindex(out.index).fillna(out["theta"])
    media_fora = media_fora.reindex(out.index).fillna(out["theta"])

    # clip evita divisão por zero para times que ainda não marcaram gols
    theta_safe = out["theta"].clip(lower=0.01)
    out["eta_m"] = media_casa / theta_safe
    out["eta_v"] = media_fora / theta_safe
    return out


# 3. Simulação dos jogos restantes

# Preenche os placares faltantes com gols ~ Poisson.
def simulate_missing_games(df, params, rng, tipo_modelo="original"):
    if tipo_modelo not in ("original", "variacao_multiplicativa"):
        raise ValueError(f"tipo_modelo desconhecido: {tipo_modelo}")

    out = df.copy()
    mask = out["gols_mandante"].isna() | out["gols_visitante"].isna()

    mandantes = out.loc[mask, "time_mandante"].values
    visitantes = out.loc[mask, "time_visitante"].values

    lam_m = (params.loc[mandantes, "theta"].values + params.loc[visitantes, "phi"].values) / 2.0
    lam_v = (params.loc[visitantes, "theta"].values + params.loc[mandantes, "phi"].values) / 2.0

    if tipo_modelo == "variacao_multiplicativa":
        lam_m = lam_m * params.loc[mandantes, "eta_m"].values
        lam_v = lam_v * params.loc[visitantes, "eta_v"].values

    out.loc[mask, "gols_mandante"] = rng.poisson(lam_m)
    out.loc[mask, "gols_visitante"] = rng.poisson(lam_v)
    return out


# 4. Classificação

# Montagem da tabela de classificação (todos os jogos com placar).

""" Critérios de desempate: pontos > vitórias > saldo de gols > gols marcados.
    O código retorna um DataFrame ordenado, indexado por time."""
def compute_standings(results, teams):
    idx = pd.Index(teams)
    n = len(teams)
    home = idx.get_indexer(results["time_mandante"])
    away = idx.get_indexer(results["time_visitante"])
    gm = results["gols_mandante"].to_numpy(dtype=int)
    gv = results["gols_visitante"].to_numpy(dtype=int)

    # soma `valores` por time (equivale a np.add.at, porém mais rápido)
    def soma(indices, valores):
        return np.bincount(indices, weights=valores, minlength=n).astype(int)

    vit_m, vit_v, empate = (gm > gv), (gv > gm), (gm == gv)

    tabela = pd.DataFrame({
        "pontos": soma(home, 3 * vit_m + empate) + soma(away, 3 * vit_v + empate),
        "vitorias": soma(home, vit_m) + soma(away, vit_v),
        "empates": soma(home, empate) + soma(away, empate),
        "derrotas": soma(home, vit_v) + soma(away, vit_m),
        "gols_marcados": soma(home, gm) + soma(away, gv),
        "gols_sofridos": soma(home, gv) + soma(away, gm),
    }, index=idx)
    tabela["saldo_gols"] = tabela["gols_marcados"] - tabela["gols_sofridos"]
    tabela.index.name = "time"

    tabela = tabela.sort_values(by=["pontos", "vitorias", "saldo_gols", "gols_marcados"],
                                ascending=False)
    tabela["posicao"] = np.arange(1, n + 1)
    return tabela


# 5. Simulação Monte Carlo

# Simulando o restante do campeonato `n_sim` vezes.
def monte_carlo_simulation(df, params, n_sim, seed=42, tipo_modelo="original"):
    teams = get_teams(df)
    n_teams = len(teams)
    rng = np.random.default_rng(seed)

    campeao_count = pd.Series(0, index=teams, dtype=int)
    rebaixado_count = pd.Series(0, index=teams, dtype=int)
    pontos_campeao = np.zeros(n_sim)
    desempate_titulo = np.zeros(n_sim, dtype=bool)

    all_points = np.zeros((n_sim, n_teams), dtype=int)
    all_is_champion = np.zeros((n_sim, n_teams), dtype=bool)
    all_not_relegated = np.ones((n_sim, n_teams), dtype=bool)
    all_is_champion[:, 0] = True                 # posição 1 = campeão
    all_not_relegated[:, -N_REBAIXADOS:] = False  # últimas posições caem

    for s in range(n_sim):
        results = simulate_missing_games(df, params, rng, tipo_modelo)
        tabela = compute_standings(results, teams)

        campeao_count[tabela.index[0]] += 1
        rebaixado_count[tabela.index[-N_REBAIXADOS:]] += 1

        pts = tabela["pontos"].to_numpy()  # já ordenado por classificação
        all_points[s] = pts
        pontos_campeao[s] = pts[0]
        desempate_titulo[s] = pts[0] == pts[1]

    return {
        "prob_campeao": (campeao_count / n_sim).sort_values(ascending=False),
        "prob_rebaixado": (rebaixado_count / n_sim).sort_values(ascending=False),
        "prob_desempate_titulo": desempate_titulo.mean(),
        "pontos_esperados_campeao": pontos_campeao.mean(),
        "pontos_campeao_dist": pontos_campeao,
        "all_points": all_points,
        "all_is_champion": all_is_champion,
        "all_not_relegated": all_not_relegated,
    }


# Calcula a pontuação mínima para um evento atingir a probabilidade alvo
def pontos_para_probabilidade(all_points, all_event, alvo):
    pontos = np.asarray(all_points).ravel()
    evento = np.asarray(all_event).ravel()

    pontos_unicos = np.sort(np.unique(pontos))
    for p in pontos_unicos:
        if evento[pontos >= p].mean() >= alvo:
            return int(p)
    return int(pontos_unicos[-1])


# 6. Bootstrap de theta e phi

# Intervalos de confiança (percentis) de theta e phi por bootstrap.

# Para cada time, reamostram-se (com reposição) os JOGOS que disputou.
def bootstrap_parameters(df, n_boot=2000, ci=0.95, seed=SEED):
    rng = np.random.default_rng(seed)
    played = played_games(df)
    alpha = 1 - ci
    quantis = [100 * alpha / 2, 100 * (1 - alpha / 2)]

    rows = []
    for team in get_teams(df):
        home = played[played["time_mandante"] == team]
        away = played[played["time_visitante"] == team]

        gols_marcados = np.concatenate([home["gols_mandante"].values, away["gols_visitante"].values])
        gols_sofridos = np.concatenate([home["gols_visitante"].values, away["gols_mandante"].values])
        n = len(gols_marcados)

        if n == 0:
            rows.append({"time": team, "theta_lo": np.nan, "theta_hi": np.nan,
                         "phi_lo": np.nan, "phi_hi": np.nan})
            continue

        sample_idx = rng.integers(0, n, size=(n_boot, n))   # (réplicas, jogos)
        theta_boot = gols_marcados[sample_idx].mean(axis=1)
        phi_boot = gols_sofridos[sample_idx].mean(axis=1)

        theta_lo, theta_hi = np.percentile(theta_boot, quantis)
        phi_lo, phi_hi = np.percentile(phi_boot, quantis)
        rows.append({"time": team, "theta_lo": theta_lo, "theta_hi": theta_hi,
                     "phi_lo": phi_lo, "phi_hi": phi_hi})

    return pd.DataFrame(rows).set_index("time")


# Gráficos

# Gráfico de barras com os 5 maiores valores
def plot_top5(serie_prob, titulo, cor):
    top5 = serie_prob.head(5) * 100
    plt.figure(figsize=(8, 5))
    bars = plt.bar(top5.index, top5.values, color=cor)
    plt.ylabel("Probabilidade (%)")
    plt.title(titulo)
    plt.xticks(rotation=30, ha="right")
    for bar, val in zip(bars, top5.values):
        plt.text(bar.get_x() + bar.get_width() / 2, val, f"{val:.1f}%",
                 ha="center", va="bottom")
    plt.tight_layout()
    plt.show()


# Histograma dos pontos do campeão nas simulações
def plot_pontos_campeao(pontos_campeao):
    plt.figure(figsize=(8, 5))
    bins = np.arange(pontos_campeao.min(), pontos_campeao.max() + 2) - 0.5
    plt.hist(pontos_campeao, bins=bins, color="#8da0cb", edgecolor="white")
    plt.axvline(pontos_campeao.mean(), color="k", linestyle="--",
                label=f"Média = {pontos_campeao.mean():.1f}")
    plt.xlabel("Pontos do campeão")
    plt.ylabel("Nº de simulações")
    plt.title("Distribuição dos pontos do campeão")
    plt.legend()
    plt.tight_layout()
    plt.show()


# IC 95% (barras) e estimativa pontual (ponto) de theta e phi por time
def plot_bootstrap_ci(boot_df, params):
    ordem = params["theta"].sort_values(ascending=False).index
    boot_df = boot_df.loc[ordem]
    theta, phi = params.loc[ordem, "theta"], params.loc[ordem, "phi"]
    y_pos = np.arange(len(boot_df))

    # clip protege contra estimativa fora do IC (caso raro)
    def erro(estimativa, lo, hi):
        return [np.clip(estimativa - lo, 0, None), np.clip(hi - estimativa, 0, None)]

    fig, axes = plt.subplots(1, 2, figsize=(14, 9), sharey=True)

    ax = axes[0]
    ax.errorbar(theta, y_pos, xerr=erro(theta, boot_df["theta_lo"], boot_df["theta_hi"]),
                fmt="o", capsize=3, color="tab:blue")
    ax.set_yticks(y_pos)
    ax.set_yticklabels(boot_df.index)
    ax.set_xlabel("theta (gols marcados / jogo)")
    ax.set_title("IC (bootstrap) - Ataque")
    ax.invert_yaxis()
    ax.grid(axis="x", alpha=0.3)

    ax = axes[1]
    ax.errorbar(phi, y_pos, xerr=erro(phi, boot_df["phi_lo"], boot_df["phi_hi"]),
                fmt="o", capsize=3, color="tab:red")
    ax.set_xlabel("phi (gols sofridos / jogo)")
    ax.set_title("IC (bootstrap) - Defesa")
    ax.grid(axis="x", alpha=0.3)

    plt.tight_layout()
    plt.show()


# Barras horizontais comparando a prob. de título (%) nos dois modelos
def plot_comparacao_modelos(tabela_comparativa, top_n=5, save_path="comparacao_modelos.png"):
    media_prob = tabela_comparativa.mean(axis=1)
    top_teams = media_prob.sort_values(ascending=False).head(top_n).index
    dados = tabela_comparativa.loc[top_teams].sort_values("Modelo Original")

    y_pos = np.arange(len(dados))
    largura = 0.35

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.barh(y_pos - largura / 2, dados["Modelo Original"], height=largura,
            label="Modelo Original", color="#66c2a5")
    ax.barh(y_pos + largura / 2, dados["Variação (η_m e η_v)"], height=largura,
            label="Variação (η_m e η_v)", color="#fc8d62")

    ax.set_yticks(y_pos)
    ax.set_yticklabels(dados.index)
    ax.set_xlabel("Probabilidade de Título (%)")
    ax.set_title("Comparação da Probabilidade de Título (%)", fontsize=14, fontweight="bold")
    ax.legend(loc="lower right")
    ax.grid(axis="x", alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.show()

"""**3. Leitura dos dados, parâmetros e classificação atual**"""

# Leitura dos dados e estimação dos parâmetros

df = load_data(CSV_PATH)
teams = get_teams(df)
n_jogados = len(played_games(df))
print(f"{len(teams)} equipes | {n_jogados}/{len(df)} jogos já realizados\n")

# theta = média de gols marcados por jogo; phi = média de gols sofridos por jogo
params = estimate_parameters(df)
print("Parâmetros estimados (theta = ataque, phi = defesa):")
display(params.sort_values("theta", ascending=False).round(3))

# Classificação usando apenas os jogos já realizados
tabela_atual = compute_standings(played_games(df), teams)
print("\nClassificação atual (parcial):")
display(tabela_atual[["pontos", "vitorias", "saldo_gols", "gols_marcados", "posicao"]])

"""**4. Monte Carlo (Perguntas 1 a 6)**"""

# Monte Carlo: simula N_SIM vezes os jogos que faltam e recalcula a classificação

print(f"Rodando {N_SIM} simulações Monte Carlo...")
res = monte_carlo_simulation(df, params, n_sim=N_SIM, seed=SEED)

# Prob. = fração das simulações em que o time terminou em 1º lugar
print("\n=== Pergunta 1: Probabilidade de cada time ser campeão ===")
display((res["prob_campeao"] * 100).round(2).rename("prob (%)"))

# Prob. = fração das simulações em que o time terminou entre os N_REBAIXADOS últimos
print("\n=== Pergunta 2: Probabilidade de cada time ser rebaixado ===")
display((res["prob_rebaixado"] * 100).round(2).rename("prob (%)"))

plot_top5(res["prob_campeao"], "Top 5 - Probabilidade de ser Campeão", "#66c2a5")
plot_top5(res["prob_rebaixado"], "Top 5 - Probabilidade de ser Rebaixado", "#fc8d62")

# "Desempate" = os dois primeiros terminam com a mesma pontuação
print("\n=== Pergunta 3: Probabilidade de empate em pontos no topo (desempate no título) ===")
print(f"{res['prob_desempate_titulo'] * 100:.2f} %")

# Média dos pontos do campeão ao longo das simulações
print("\n=== Pergunta 4: Número esperado de pontos do campeão ===")
print(f"{res['pontos_esperados_campeao']:.2f} pontos")
plot_pontos_campeao(res["pontos_campeao_dist"])

# Menor pontuação p tal que P(ser campeão | terminar com >= p pontos) >= 90%
pontos_90 = pontos_para_probabilidade(res["all_points"], res["all_is_champion"], alvo=0.90)
print("\n=== Pergunta 5: Pontos necessários para >=90% de chance de ser campeão ===")
print(f"{pontos_90} pontos")

# Menor pontuação p tal que P(não ser rebaixado | terminar com >= p pontos) >= 95%
pontos_95 = pontos_para_probabilidade(res["all_points"], res["all_not_relegated"], alvo=0.95)
print("\n=== Pergunta 6: Pontos necessários para >=95% de chance de NÃO ser rebaixado ===")
print(f"{pontos_95} pontos")

"""**5. Bootstrap**"""

# Bootstrap: incerteza (IC 95%) das estimativas de theta e phi
print(f"Rodando bootstrap ({N_BOOT} réplicas por time)...")
boot_df = bootstrap_parameters(df, n_boot=N_BOOT, seed=SEED)
display(boot_df.round(3))
plot_bootstrap_ci(boot_df, params)

"""**6. Atividade extra (eta_m e eta_v)**"""

# Atividade extra: modelo com eficiência ofensiva em casa/fora (eta_m e eta_v)

# eta > 1: o time ataca melhor naquele mando do que na média geral
params_extra = estimate_extra_parameters(df, params)
print("Parâmetros extras (eta_m = eficiência em casa, eta_v = eficiência fora):")
display(params_extra[["theta", "phi", "eta_m", "eta_v"]].round(3))

print(f"\nRodando {N_SIM} simulações para cada modelo...")
res_original = monte_carlo_simulation(df, params_extra, N_SIM, seed=SEED, tipo_modelo="original")
res_variacao = monte_carlo_simulation(df, params_extra, N_SIM, seed=SEED, tipo_modelo="variacao_multiplicativa")

tabela_comparativa = pd.DataFrame({
    "Modelo Original": res_original["prob_campeao"] * 100,
    "Variação (η_m e η_v)": res_variacao["prob_campeao"] * 100,
})

# Mantém só times com chance > 0 de título em pelo menos um dos modelos
tabela_comparativa = tabela_comparativa[
    (tabela_comparativa["Modelo Original"] > 0) | (tabela_comparativa["Variação (η_m e η_v)"] > 0)
].sort_values("Modelo Original", ascending=False)

print("\nTabela comparativa dos 2 modelos:")
display(tabela_comparativa.round(2))

plot_comparacao_modelos(tabela_comparativa, top_n=5)